### ISSUE TITLE
Arch AUR PKGBUILD for source package without Docker

### ISSUE THREAD

**Issue by HanPrower** [kostoskistefan/hoverclock-qt#11]
So, I was fiddling, and must admit to get this to work correctly took me way longer than it should have. The xcb ENV setting evaded me for a while as I'm on Wayland, but I managed to get it to work correctly(?).

I'm posting it here first, instead of just submitting in case you'd rather maintain it, else I can submit to the AUR if that's okay.

```
# Maintainer: HanFox <han at hanfox dot co dot uk>

pkgname=hoverclock
pkgver=0.0.5
pkgrel=1
pkgdesc='A simple, yet customisable floating clock created with Qt.'
arch=('x86_64')
url='https://github.com/kostoskistefan/hoverclock'
license=(GPL3)
depends=(hicolor-icon-theme qt5-base)
source=("$pkgname-$pkgver.tar.gz::https://github.com/kostoskistefan/$pkgname/archive/refs/tags/v$pkgver.tar.gz")
sha256sums=('5b1b66647337799daeda0ecb08c3b8b09cf91506647dec75bbbc62e8a3cc30d1')

build() {
    cd "$pkgname-$pkgver/src"
    qmake
    make
}

package() {
    cd "$srcdir"

    # Install Binary
    install -Dm755 "$pkgname-$pkgver/src/$pkgname" "$pkgdir/usr/bin/$pkgname"
    
    # Install Icons
    install -Dm644 "$pkgname-$pkgver/src/resources/icons/$pkgname.png" "$pkgdir/usr/share/icons/hicolor/512x512/apps/$pkgname.png"
    install -Dm644 "$pkgname-$pkgver/src/resources/icons/$pkgname.svg" "$pkgdir/usr/share/icons/hicolor/scalable/apps/$pkgname.svg"
    
    # Install Desktop Shortcut
    sed -i -E "s|Exec=hoverclock|Exec=env QT_QPA_PLATFORM=xcb hoverclock|" "$pkgname-$pkgver/$pkgname.desktop"
    install -Dm644 "$pkgname-$pkgver/$pkgname.desktop" -t "$pkgdir/usr/share/applications/"
}
```

**Comment by kostoskistefan** [comment]
Awesome work that you made a PKGBUILD to build the app from source, but I think you should hold on before posting it to the AUR, because a lot of things are probably going to change, including the build process and dependencies. 

I created an AUR package from the AppImage, because I think I'll continue to deploy it that way in the future. At some point, I might add .deb or .rpm packages, but for now I'll stick with the AppImage since there are more important features to be implemented first.

There are also a few issues with the icons that I'm trying to fix, and that means that the PKGBUILD file will need to be changed a lot.

I'm working on features every day and a lot of things change quite a bit, since it's still very early in the development process. I had to change the Makefile (not the one generated by QMake, but the one used for building everything in the docker container) a few times to make everything work, and I think that until I create a stable Makefile, people should use the AppImage either from the releases section on Github, or the AUR package hoverclock-appimage.

I won't close this issue for now and I'll notify you once there is a more stable architecture for the whole project.

But thank you for the submission anyways, it's very useful.

**Comment by HanPrower** [comment]
Yup, totally understandable. Pretty much why I asked first instead of just submitting it :smile:
