### ISSUE TITLE
Icon and app picker for block

### ISSUE THREAD

**Issue by docop** [kostoskistefan/hoverclock-qt#16]
As mention, so for improved you asked: the taskbar icon : with the toggle visibility.. perhaps making the circle a dim red. Current dim gray, but when we toggle visibily (to turn off) : having the circle turn red (dim red or dark red...) can be great.

And perhaps another point, if that easy.. The block list: have an option to list the current opened soft.. or best a soft picker and we just select other appimage needed.. Like in xfce, when you click something, the menu appear to ask to open with what. Perhaps a kind of call to get the same idea of a menu and pick the soft to exclude directly from that.. 
thanks

**Comment by kostoskistefan** [comment]
As for the first suggestion, it is very much doable. I'm currently working on a different functionality, but I'll add dynamic color to the tray icon in the near future.

About the second issue. Since every desktop environment has a different dialog that shows installed apps, I'd have to write code for every single desktop environment out there. There are some workarounds, like listing the .desktop files, or listing the running processes with the `ps` command and making my own app picker dialog, but I'm still looking for better alternatives.

For now, it's going to remain as is, because it'll work on every desktop environment and will support as many users as possible.

**Comment by kostoskistefan** [comment]
I've added dimming of the system tray icon depending on the visibility of the clock. However, I did not make it red, because many people might use themes with different color highlights.
