### ISSUE TITLE
Feature request - Add battery

### ISSUE THREAD

**Issue by jorisvandijk** [kostoskistefan/hoverclock-qt#19]
I know it's called hoverCLOCK, but I would love to have an option to also show the current battery status using acpi.

**Comment by kostoskistefan** [comment]
Hey, thank you for the request! 

I'm currently working on fixing a bug with the system tray, which is my top priority with this project at the moment.
After fixing that, I'll try to implement your request. 

Although I'm not sure if I'll add it to the main branch (or even in this project altogether), because as you said, it's hoverCLOCK, and the main goal was to have a simple, customizable clock (and date).

Many people still use desktop computers which, as you know, don't have a battery. That would make this feature useless to them, so I'm sure you understand my dilemma.

I'll keep this issue open until I have more time to do a bit of research on getting battery info and I'll update you accordingly.

**Comment by kostoskistefan** [comment]
After some consideration and research, I came to a conclusion to **NOT** implement the battery indicator. 

HoverCLOCK was made to be just that. **A clock**. 

I don't think many people will find a battery indicator useful, especially inside a software created for displaying the time and date. And as I've previously stated, not everyone uses portable devices.

Maybe some day I'll create a hovering battery indicator, but for now, I still want to improve and optimize the current features of Hoverclock. I hope you understand.
