### ISSUE TITLE
Cannot access to the configurations

### ISSUE THREAD

**Issue by MarkGrn** [kostoskistefan/hoverclock-qt#24]
System: linux mint.
```
$ uname -a
Linux O28 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
I'm trying to access the setting of the hoverclock to change its appearance. I can see the hoverclock at the right bottom of the screen but its to small for me. I don't see any icon of the hoverclock in the system tray. I went to the installation folder located in  
/home/{user}/Hoverclock and tried to execute `sudo ./hoverclock.sh -c` and I'm getting 
`./hoverclock.sh -c
An instance is already running.
`
What I'm doing wrong?

**Comment by kostoskistefan** [comment]
Hoverclock allows only one instance to be running at a particular time. Starting it using the `-c` option tries to launch a new instance, but it detects that an instance is already running and therefore it cancels the launch operation and you get the error message.

To fix this, you should first close the existing instance, then execute the `sudo ./hoverclock.sh -c` command.

Since for some reason you don't have the icon in the system tray, you can firstly run `pkill hoverclock` to kill the running instance and then execute the previous command to launch a new instance of hoverclock with the settings dialog opened.

**Comment by MarkGrn** [comment]
Thanks a lot, your clock is awesome <3
